### ISSUE TITLE
Mantainer Permission

### ISSUE THREAD

**Issue by rodfersou** [asdf-community/asdf-ubuntu#3]
hello @vic can I join as mantainer of this project? I have interest to build a series of languages and versions, also update the images.

Rodrigo

**Comment by vic** [comment]
Hey Rodrigo, for sure! I'll add you as collaborator so you can merge your own merge requests and/or push directly.

The main idea for this repo (and sister `asdf-alpine` repo) was having a repo  of pre-compiled asdf tools (at least for ubuntu/alpine but I guess it'd be possible also for macos) that you could easily use to avoid re-compiling tools that are only installable via source. Back in those days I was using erlang/elixir a lot and particularly the first one was taking a lot of time
to compile, and creating docker images having those tools was way slow. So I created these repos and some scripts (the travis.yml that these days might be much better migrated to github actions) to ease creating some of my asdf-powered-docker-images.

Nowadays many asdf plugins (at least those we have on asdf-community) use the `plugin_test` action (from asdf-actions) which tests primarily on ubuntu-latest and macos-latest. I would be awesome if we could somehow provide pre-built tools based on these, since anyways those tools get built an tested.

Something to consider here would be
1) having a fixed asdf home location - this repo does that- (perhaps akin to /nix on nixos) 
2) having a place to store all those precompiled packages and make they available for download.
  For this maybe could created another action on `asdf-actions` that simply packages the compiled tools (since anyways they are being compiled for `plugin-test`) and upload those packages as github artifacts (on the each respective plugin repository). 

Dunno, that's all I can remember thinking about when working on this repo, I'll leave all this to your consideration.

**Comment by rodfersou** [comment]
thanks very much!

for now my objective will be to add new images, I have been compiling many tools with asdf-vm lately, and want to consolidate it in docker hub (since when jump from linux to macos the compile history change a lot).

**Comment by rodfersou** [comment]
@vic I still can't merge, also noticed that my name is not here: https://github.com/orgs/asdf-community/people

**Comment by vic** [comment]
Looks like you haven't accepted the invitation as Maintainer, check your inbox for a mail from github.

<img width="1194" alt="Screen Shot 2020-07-09 at 10 09 22" src="https://user-images.githubusercontent.com/331/87057409-704ff980-c1cc-11ea-9158-c3729194f77c.png">

**Comment by rodfersou** [comment]
![image](https://user-images.githubusercontent.com/131209/87113850-6516cf80-c299-11ea-810f-577526d58bf6.png)
Invitation expired.. 😄

**Comment by rodfersou** [comment]
@vic can you please invite me again?

**Comment by vic** [comment]
@rodfersou just sent another one, check it out ! :)

**Comment by rodfersou** [comment]
now this works for this package, but not for others, I'm not listed in the [asdf-community list](https://github.com/orgs/asdf-community/people)

well, I'll work more on this repository, so don't see a problem, although maybe `asdf-alpine` repo should be interesting to have permission.
